// hologram/config.js — LT Hologram configuration
// Invariant: all magic numbers centralized. Templates frozen.

const HOLO_CFG = Object.freeze({
  ENTITY_TYPE:     "lt:hologram",
  ADMIN_TAG:       "mimi",
  UPDATE_INTERVAL: 100,
  RESPAWN_DELAY:   80,
  MAX_HOLOS:       50,
  MAX_LINES:       20,
  MAX_TEXT_LEN:    200,
  PROXIMITY_RANGE: 16,
  VIEW_RANGE:      48, // default render distance (blocks) — skip update if no player in range
  COIN_OBJ:        "coin",
  GEM_OBJ:         "gem",
  K_REGISTRY:      "lt_holo:reg",

  TAG_ID:   "lh_id:",
  TAG_HOLO: "lh",

  CYCLE_COLORS: Object.freeze(["§c", "§6", "§e", "§a", "§b", "§d", "§5"]),

  // Alignment pad char — thin space for consistent visual width
  PAD_CHAR: " ",
  PAD_MAX:  40, // max padding chars per side

  ALIGNS: Object.freeze({
    center: "Tengah",
    left:   "Kiri",
    right:  "Kanan",
  }),

  PLACEHOLDERS: Object.freeze({
    "{online}":      "Jumlah player online",
    "{time}":        "Waktu WIB (HH:MM)",
    "{date}":        "Tanggal (DD/MM/YYYY)",
    "{day_count}":   "Hari dunia",
    "{top:OBJ:N}":   "Leaderboard top N dari OBJ",
    "{my:OBJ}":      "Skor player terdekat dari OBJ",
    "{my_name}":     "Nama player terdekat",
    "{day|A|B}":     "Tampil A siang, B malam",
  }),

  ANIMATIONS: Object.freeze({
    none:  "Statis",
    cycle: "Cycle warna",
  }),

  VIEW_RANGES: Object.freeze({
    16:  "16 blok (dekat)",
    32:  "32 blok",
    48:  "48 blok (default)",
    64:  "64 blok",
    128: "128 blok (jauh)",
    0:   "Tanpa batas",
  }),

  TEMPLATES: Object.freeze({
    welcome: Object.freeze({
      name: "Welcome",
      desc: "Selamat datang + info server",
      align: "center",
      lines: Object.freeze([
        "",
        "§l§6L A U G H T A L E",
        "§r§8S U R V I V A L   M U L T I P L A Y E R",
        "",
        "§r§8───────────────────────",
        "",
        "§r§fSelamat datang, petualang!",
        "§r§a{online} §7player sedang online",
        "",
        "§r§8───────────────────────",
        "",
        "§r§e/daily §8........ §7Hadiah login",
        "§r§e/bank §8......... §7Transfer koin",
        "§r§e/store §8........ §7Beli material",
        "§r§e/lt:gacha §8..... §7Gacha item",
        "§r§e/lt:auction §8... §7Lelang",
        "",
        "§r§8───────────────────────",
        "§r§7{day|§a* Server OPEN|§c* Server CLOSED}",
        "",
      ]),
    }),
    rules: Object.freeze({
      name: "Rules",
      desc: "Peraturan server",
      align: "center",
      lines: Object.freeze([
        "",
        "§l§cP E R A T U R A N",
        "§r§8S E R V E R",
        "",
        "§r§8───────────────────────",
        "",
        "§r§f1 §8>> §7Dilarang cheat dan hack",
        "§r§f2 §8>> §7Dilarang grief area lain",
        "§r§f3 §8>> §7Hormati sesama player",
        "§r§f4 §8>> §7Gunakan bahasa sopan",
        "§r§f5 §8>> §7Jual beli hanya via §f/bank",
        "",
        "§r§8───────────────────────",
        "§r§c>> Pelanggaran = BAN <<",
        "",
      ]),
    }),
    shop: Object.freeze({
      name: "Shop",
      desc: "Info area toko",
      align: "center",
      lines: Object.freeze([
        "",
        "§l§eS H O P   A R E A",
        "",
        "§r§8───────────────────────",
        "",
        "§r§bGacha §8......... §7Partikel & Equip",
        "§r§eStore §8......... §7Bahan building",
        "§r§6Auction §8....... §7Jual beli player",
        "",
        "§r§8───────────────────────",
        "§r§7Ketik §f/lt:gacha §7untuk mulai",
        "",
      ]),
    }),
    info: Object.freeze({
      name: "Server Info",
      desc: "Info live server realtime",
      align: "center",
      lines: Object.freeze([
        "",
        "§l§bS E R V E R   I N F O",
        "",
        "§r§8───────────────────────",
        "",
        "§r§a{online} §fplayer online",
        "§r§f{time} §7WIB",
        "§r§f{date}",
        "§r§7Hari ke-§e{day_count}",
        "",
        "§r§8───────────────────────",
        "§r{day|§a* Server OPEN|§c* Server CLOSED}",
        "",
      ]),
    }),
    lb_coin: Object.freeze({
      name: "Top Koin",
      desc: "Leaderboard koin top 10",
      align: "center",
      lines: Object.freeze([
        "",
        "§l§6T O P   1 0   K O I N",
        "",
        "§r§8───────────────────────",
        "",
        "{top:coin:10}",
        "",
        "§r§8───────────────────────",
        "",
      ]),
    }),
    lb_kills: Object.freeze({
      name: "Top Kills",
      desc: "Leaderboard kills top 10",
      align: "center",
      lines: Object.freeze([
        "",
        "§l§cT O P   1 0   K I L L S",
        "",
        "§r§8───────────────────────",
        "",
        "{top:kills:10}",
        "",
        "§r§8───────────────────────",
        "",
      ]),
    }),
    mystats: Object.freeze({
      name: "My Stats",
      desc: "Statistik player terdekat",
      align: "center",
      lines: Object.freeze([
        "",
        "§l§bS T A T S   K A M U",
        "",
        "§r§8───────────────────────",
        "",
        "§r§f{my_name}",
        "",
        "§r§eKoin §8... §f{my:coin}",
        "§r§bGem §8.... §f{my:gem}",
        "",
        "§r§8───────────────────────",
        "§r{day|§a* OPEN|§c* CLOSED}",
        "",
      ]),
    }),
    social: Object.freeze({
      name: "Social",
      desc: "Link komunitas",
      align: "center",
      lines: Object.freeze([
        "",
        "§l§dK O M U N I T A S",
        "",
        "§r§8───────────────────────",
        "",
        "§r§9Discord §8... §7discord.gg/laughtale",
        "§r§cYouTube §8... §7@LaughtaleSMP",
        "§r§bInstagram §8. §7@laughtale.smp",
        "",
        "§r§8───────────────────────",
        "",
      ]),
    }),
  }),

  HR:      "§8═══════════════════",
  HR_THIN: "§8───────────────────",
});

export { HOLO_CFG };
